// https://claude.ai/chat/f74a37ec-1746-48b6-92af-6a933d5da401
export const CARD_TOPICS = {
    "programming languages": [
    "JavaScript",
    "Python",
    "HTML",
    "CSS",
    "SQL",
    "Java",
    "TypeScript",
    "C#",
    "C++",
    "PHP",
    "C",
    "Go",
    "Rust",
    "Ruby",
    "Swift",
    "Kotlin",
    "R",
    "MATLAB",
    "Shell",
    "Bash",
    "PowerShell",
    "Scala",
    "Dart",
    "JSON",
    "XML",
    "YAML",
    "Perl",
    "Lua",
    "Groovy",
    "Objective-C",
    "Visual Basic .NET",
    "Assembly",
    "Haskell",
    "Julia",
    "COBOL",
    "Fortran",
    "Elixir",
    "Clojure",
    "F#",
    "Delphi",
    "Crystal",
    "Solidity",
    "GraphQL",
    "Lisp",
    "ABAP",
    "PL/SQL",
    "Prolog",
    "Apex",
    "SAS",
    "Erlang"
  ],
  "web development and software engineering": [
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Web Frameworks",
    "Mobile Development",
    "Cloud Computing",
    "DevOps",
    "Databases",
    "Web Security",
    "API Design",
    "Microservices",
    "Algorithms",
    "Data Structures",
    "Machine Learning",
    "Testing",
    "Performance Optimization",
    "UI/UX Design",
    "Responsive Design",
    "Accessibility",
    "Version Control",
    "Containerization",
    "Continuous Integration/Deployment",
    "Software Architecture",
    "Agile Methodologies",
    "Data Engineering"
  ],
  "web frameworks and libraries": [
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Next.js",
    "Svelte",
    "Django",
    "Ruby on Rails",
    "Laravel",
    "Flask",
    "Spring Boot",
    "ASP.NET Core",
    "Redux",
    "TailwindCSS",
    "Bootstrap",
    "jQuery",
    "Material UI",
    "GraphQL",
    "NestJS",
    "Gatsby",
    "Nuxt.js",
    "FastAPI",
    "Remix",
    "Astro"
  ]
};

export const CARD_TOPICS_AGGREGATED = Object.keys(CARD_TOPICS).reduce((total, key) => total.concat(CARD_TOPICS[key]), []);

  